name: "Check assets and verify"
on: [push]
jobs:
  assests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          architecture: x64
        - name: Install dependencies
          run: |
            pip install -r requirements.txt